### ISSUE TITLE
Clean up the hardcoded configuration information

### ISSUE THREAD

**Issue by nguyenLisa** [nguyenLisa/abm#11]
Do not duplicate the hardcoded configuration information.
Folders such as /var/lib/abm/... should not be hardcoded in the code (e.g., bnd-workspace/de.fraunhofer.abm.hermes/src/de/fraunhofer/abm/hermes/impl/RunDocker.java). They should be retrieved from the Configuration files.

**Comment by ankur-1989** [comment]
Now I have started looking into it.

**Comment by ankur-1989** [comment]
Fixed the changes and pushed the changes to master branch. Tested the changes on local. will push the changes to production branch with solution of issue #13. Closing this issue now. Now we only need to change in HermesConfiguration.java file.

**Comment by nguyenLisa** [comment]
Thanks for cleaning up /opt/abm. 
Could you also add /var/lib/... in the configuration file as well? It can still be found here: https://github.com/nguyenLisa/abm/blob/master/bnd-workspace/de.fraunhofer.abm.suitebuilder/src/de/fraunhofer/abm/suitebuilder/impl/Configuration.java#L20 and here: https://github.com/nguyenLisa/abm/blob/32c7c61f01ef72f3cfefb2836fc66f76beb4fc77/bnd-workspace/de.fraunhofer.abm.repoarchive.local/src/de/fraunhofer/abm/repoarchive/local/Configuration.java#L11

**Comment by ankur-1989** [comment]
I went through the documentation of Osgi enroute framework but i found this is the better way that we are using currently for defining configurations for individual components I tried different ways but other methods  do not set the configuration data on component registration. Should we keep it like this ?otherwise I will have to change the structure of passing the configuration data which is not a good idea.

**Comment by nguyenLisa** [comment]
In that case, please keep the configuration information in separate files then.

**Comment by ankur-1989** [comment]
ok. It is done then. shall I close this ticket ?

**Comment by nguyenLisa** [comment]
Yes, you can close the ticket. Before that, please also update the Configuration section of the developer manual to document your changes.

**Comment by ankur-1989** [comment]
In current set up , we dont need to set the directory path or need to create if the required directory structure is not there. application will itself create the directory structure and application will run fine.

**Comment by nguyenLisa** [comment]
Thanks for the information. Please make a note of that in the developer manual.

**Comment by ankur-1989** [comment]
Developer manual updated with the information.
