### ISSUE TITLE
Build tabs are too small to show the name of the collection

### ISSUE THREAD

**Issue by nguyenLisa** [nguyenLisa/abm#15]
The build tabs are too small to show the full name of a collection. They should no longer contain the word "Building", to make more space. A tooltip should show the name of the collection on hover.

<img width="178" alt="capture d ecran 2018-01-26 a 18 41 29" src="https://user-images.githubusercontent.com/1546847/35452908-8ca7c812-02c8-11e8-86df-11e3e526c982.png">

**Comment by tylerpav** [comment]
I have managed to get the build text removed and the tooltip to appear when the Build Viewer Modal is present, however I am currently unable to get the tooltip to populate when still on the edit collections page. The current changes are done in modalBuildViewer.htm and TabTitleFilter.js, is there a reason that the div that is being populated through the BuildTabController.js would differ from the Modal's for the sidebar?

**Comment by nguyenLisa** [comment]
Can you show me what kind of code you use for the tooltips?
Off the top of my head, I can suggest you check for the style of your div, perhaps the z-index is a bit too big, or perhaps the hover event is not firing. You can check the latter with the Chrome inspect console.

**Comment by tylerpav** [comment]
I just didn't think to check index.html for any sidebar code because I thought it was only on the edit collection page. It was all just really a matter of finding where it was other than the build view modal.

I just used the title attribute on the div that gets repeated, setting it to tab.name

**Comment by nguyenLisa** [comment]
So is it working now?

**Comment by tylerpav** [comment]
Yes it is

**Comment by nguyenLisa** [comment]
Great! Thanks for your work. Feel free to create a pull request and to close the issue.
