### ISSUE TITLE
Hermes results "Failed with 404, not found"

### ISSUE THREAD

**Issue by nguyenLisa** [nguyenLisa/abm#23]
When clicking on the button "Show Hermes Results", there is a "Failed with 404, not found" error, although the results download works.

**Comment by ankur-1989** [comment]
Hermes configuration file was missing therefore issue was coming. have placed the file , it is working now.

**Comment by ankur-1989** [comment]
Shall I close this issue now ??

**Comment by nguyenLisa** [comment]
Yes. Can you push the changes to the prod machine as well?

**Comment by ankur-1989** [comment]
yes i placed the file on prod only and tested on abm server.

**Comment by nguyenLisa** [comment]
Thanks! Feel free to close the issue.
