### ISSUE TITLE
Remove enumeration of available REST services

### ISSUE THREAD

**Issue by bhermann** [nguyenLisa/abm#28]
A request to /rest/ (e.g. https://abm.cs.upb.de/rest/) reveals the available REST services. It is not considered good practice to reveal the list of possible endpoints to the client. 

Please remove this list from the server's response.

**Comment by bhermann** [comment]
It might also be okay to filter this error using the apache server on the deployed instance.
If we choose this solution, however, we should mark this in the installation manual.

**Comment by nguyenLisa** [comment]
Fixed through the Apache configurations. The developer manual has been updated as well.
