### ISSUE TITLE
Update the information in the About page

### ISSUE THREAD

**Issue by nguyenLisa** [nguyenLisa/abm#32]
- Add Ben in the "Contact information" section.
- Supported platforms are Github, Maven, Bitbucket.
- Add Hermes (https://dl.acm.org/citation.cfm?id=3088523) to the publications list.
- Make mention of this open-source repository in the "How can I contribute?" section.
- If anything is not clear to you in the About page, feel free to reformulate it.

**Comment by SwapnilShahGit** [comment]
@bhermann What is the email address I should add to your contact information?

**Comment by SwapnilShahGit** [comment]
After some stalking, going to add "ben.hermann@uni-paderborn.de". Please let me know if there is a different one you would like me to add.

**Comment by SwapnilShahGit** [comment]
@nguyenLisa what do you mean by "Supported platforms are not Github, Maven, Bitbucket."

**Comment by nguyenLisa** [comment]
Sorry, I meant "Supported platforms are Github, Maven, Bitbucket."
The email address for Ben is the correct one. Thanks.
